import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');
const server=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'31829',HOST:'127.0.0.1'},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
try{
 await once(server.stdout,'data');browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1180,height:820},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/app.js?*',async r=>r.fulfill({contentType:'text/javascript',body:await readFile('dist/app.js','utf8')+`
window.cityQA={body:()=>lastState.players.find(p=>p.id===myId),walk:(x,z)=>{yaw=0;keys.clear();if(x)keys.add(x>0?'KeyD':'KeyA');if(z)keys.add(z>0?'KeyS':'KeyW')},view:()=>({fov:camera.fov,base:prefs.fov,model:gunAttachments,effects:effects.length}),look:(y,p)=>{yaw=y;pitch=p}};const realShot=shotEffect;shotEffect=m=>{window.lastQAShot=m;realShot(m)};`}));
 await page.goto('http://127.0.0.1:31829');await page.getByText('SUNUCU ÇEVRİMİÇİ',{exact:true}).waitFor();
 await page.locator('#nickname').fill('City QA');await page.locator('#preferredTeam').selectOption('blue');await page.locator('#createButton').tap();await page.locator('[name=name]').fill('City attachments QA');await page.locator('[name=mode]').selectOption('tdm');await page.locator('[name=map]').selectOption('city');await page.locator('#botCount').fill('0');await page.locator('#createForm button[type=submit]').tap();await page.locator('#resume').tap();
 async function walkTo(x,z){for(let n=0;n<420;n++){const p=await page.evaluate(()=>cityQA.body()),dx=x-p.x,dz=z-p.z;if(Math.hypot(dx,dz)<.7){await page.evaluate(()=>cityQA.walk(0,0));return;}await page.evaluate(([x,z])=>cityQA.walk(Math.abs(x)>.2?Math.sign(x):0,Math.abs(z)>.2?Math.sign(z):0),[dx,dz]);await page.waitForTimeout(65);}throw Error('Could not reach '+x+','+z);}
 const initial=await page.evaluate(()=>cityQA.body());assert.ok(initial.z>60);
 for(const [kind,x]of [['extended',16],['scope',0],['suppressor',-16]]){await walkTo(x,65.2);await page.locator('#pickupAttachment').waitFor({state:'visible'});await page.locator('#pickupAttachment').tap();await page.waitForFunction(k=>cityQA.body().attachments?.rifle?.[k],kind);console.log('PASS: touch pickup '+kind);}
 await page.locator('#touchReload').tap();await page.waitForFunction(()=>cityQA.body().ammo===45);assert.equal((await page.evaluate(()=>cityQA.body())).reserve,75);
 await page.locator('#touchAim').tap();await page.waitForFunction(()=>cityQA.view().fov<55);assert.equal(await page.locator('#scope').isVisible(),true);await page.screenshot({path:'artifacts/city-scope-mobile.png'});await page.locator('#touchAim').tap();
 await page.evaluate(()=>cityQA.look(Math.PI,0));await page.waitForTimeout(300);const fire=await page.locator('#touchFire').boundingBox();await page.mouse.move(fire.x+fire.width/2,fire.y+fire.height/2);await page.mouse.down();await page.waitForFunction(()=>cityQA.body().ammo<45);await page.mouse.up();await page.waitForFunction(()=>window.lastQAShot?.suppressed&&window.lastQAShot?.surface);assert.ok((await page.evaluate(()=>cityQA.view())).effects>0);assert.equal((await page.evaluate(()=>cityQA.body())).money,initial.money);
 await page.evaluate(()=>cityQA.look(0,0));await page.screenshot({path:'artifacts/city-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: city mobile, 3 physical pickups, 45-round reload, 2x optic, suppressed shot, server-confirmed wall decal and no runtime errors');
 const gallery=await browser.newPage({viewport:{width:1400,height:1000}});await gallery.route('**/city-gallery',r=>r.fulfill({contentType:'text/html',body:`<html><head><script type="importmap">{"imports":{"three":"/vendor/three.module.js"}}</script></head><body style="margin:0"><script type="module" src="/city-gallery.js"></script></body></html>`}));await gallery.route('**/city-gallery.js',r=>r.fulfill({contentType:'text/javascript',body:`import * as THREE from 'three';import {buildArena} from '/arena.js';const scene=new THREE.Scene();buildArena(scene,'city');scene.fog=null;scene.add(new THREE.HemisphereLight(0xdcefff,0x555555,3));const light=new THREE.DirectionalLight(0xffedce,3);light.position.set(20,80,25);scene.add(light);const camera=new THREE.PerspectiveCamera(57,1.4,.1,400);camera.position.set(96,112,125);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(1400,1000);document.body.append(renderer.domElement);renderer.render(scene,camera);window.ready=true;`}));await gallery.goto('http://127.0.0.1:31829/city-gallery');await gallery.waitForFunction(()=>window.ready);await gallery.screenshot({path:'artifacts/city-overview.png'});
}finally{await browser?.close();server.kill()}
