import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');
const server=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'31819',HOST:'127.0.0.1'},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
try{
 await once(server.stdout,'data');browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/app.js?*',async route=>route.fulfill({contentType:'text/javascript',body:await readFile('dist/app.js','utf8')+`
window.qa={rejoin:id=>requestJoin(id,'test-only-password'),disconnect:()=>socket.close(),room:()=>room?.id,prefs:()=>({...mobilePrefs}),camera:()=>({x:camera.position.x,y:camera.position.y,z:camera.position.z}),fixture:()=>{window.frozen=true;lastState.mode='rounds';body.hp=0;lastState.players=[body,{...body,id:'ally1',name:'Bir',hp:100,x:3,y:0,z:2,pitch:0,yaw:0},{...body,id:'ally2',name:'İki',hp:80,x:5,y:0,z:2,pitch:0,yaw:0},{...body,id:'enemy',name:'Rakip',team:body.team==='blue'?'orange':'blue',hp:100}];},kill:()=>lastState.players[1].hp=0,alive:()=>{body.hp=100;window.frozen=false}};const receiveLive=receiveState;receiveState=s=>{if(!window.frozen)receiveLive(s)};`}));
 await page.goto('http://127.0.0.1:31819');await page.getByText('SUNUCU ÇEVRİMİÇİ',{exact:true}).waitFor();
 await page.locator('#settingsButton').tap();await page.locator('#touchSensitivity').fill('1.8');await page.locator('#touchSize').fill('1.1');await page.locator('#touchLayout').selectOption('left');await page.reload();await page.getByText('SUNUCU ÇEVRİMİÇİ',{exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>qa.prefs()),{sensitivity:1.8,size:1.1,layout:'left'});assert.equal(await page.locator('#sensitivity').inputValue(),'1');
 await page.locator('#nickname').fill('Recovery QA');await page.locator('#createButton').tap();await page.locator('[name=name]').fill('Private recovery');await page.locator('#createForm [name=password]').fill('test-only-password');await page.locator('[name=mode]').selectOption('tdm');await page.locator('#botCount').fill('0');await page.locator('#createForm button[type=submit]').tap();await page.locator('#resume').waitFor({state:'visible'});const room=await page.evaluate(()=>qa.room());
 await page.evaluate(()=>qa.disconnect());await page.locator('#recoveryPanel').waitFor({state:'visible'});await page.waitForFunction(id=>qa.room()===id,room);await page.locator('#recoveryPanel').waitFor({state:'hidden'});await page.locator('#resume').tap();
 const stick=await page.locator('#moveStick').boundingBox(),fire=await page.locator('#touchFire').boundingBox();assert.ok(stick.x>fire.x,'Left-handed layout mirrors controls');
 await page.evaluate(()=>qa.fixture());await page.locator('#spectatorOptions').waitFor({state:'visible'});await page.locator('#spectatorNext').tap();await page.waitForFunction(()=>document.getElementById('spectatorName').textContent.startsWith('Bir'));assert.equal((await page.evaluate(()=>qa.camera())).x,3);
 await page.evaluate(()=>qa.kill());await page.waitForFunction(()=>document.getElementById('spectatorName').textContent.startsWith('İki'));assert.equal((await page.evaluate(()=>qa.camera())).x,5);await page.locator('#spectatorFree').tap();await page.waitForFunction(()=>document.getElementById('spectatorFree').getAttribute('aria-pressed')==='true');await page.screenshot({path:'artifacts/spectator-options.png'});await page.evaluate(()=>qa.alive());await page.locator('#spectatorOptions').waitFor({state:'hidden'});
 await page.evaluate(()=>qa.disconnect());await page.locator('#recoveryPanel').waitFor({state:'visible'});await page.locator('#recoveryPanel button').tap();await page.waitForTimeout(1800);assert.equal(await page.evaluate(()=>qa.room()),undefined);await page.evaluate(id=>qa.rejoin(id),room);await page.waitForFunction(id=>qa.room()===id,room);
 await page.locator('#leave').tap();await page.evaluate(()=>qa.disconnect());await page.waitForTimeout(1800);assert.equal(await page.evaluate(()=>qa.room()),undefined);assert.equal(await page.locator('#recoveryPanel').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS: persisted independent mobile preferences, mirrored controls, password-room reconnection, teammate-only follow, death fallback, free camera, respawn cleanup, intentional leave.');
}finally{await browser?.close();server.kill();}
